on:
  push:
    branches: [ develop, bugfix/*, feature/*, release/*, dependabot/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build-validation:
    uses: abbgrade/PsBuildTasks/.github/workflows/build-validation-windows.yml@1.10.0
