on:
  push:
    branches: [ develop, bugfix/*, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build-validation:
    uses: abbgrade/PsBuildTasks/.github/workflows/build-validation-matrix.yml@673a69e34214986b0db3a0a8266d4dd9603cc7a8
