on:
  push:
    branches: [ main, 'hotfix/*' ]
  workflow_dispatch:

jobs:
  release:
    uses: abbgrade/PsBuildTasks/.github/workflows/release-windows.yml@1.13.0
    with:
      module-name: MyModuleName
    secrets:
      ps-gallery-key: ${{ secrets.PS_GALLERY_KEY }}
