on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install build dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -ErrorAction Stop
          Invoke-Build InstallBuildDependencies -Verbose

      - name: Create build
        shell: pwsh
        run: Invoke-Build Build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          path: publish
          name: ${{ matrix.os }}-build
  test:
    needs: build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          path: publish
          name: ${{ matrix.os }}-build

      - name: Install test dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -ErrorAction Stop
          Invoke-Build InstallTestDependencies -Verbose

      - name: Test module
        shell: pwsh
        run: |
            $config = New-PesterConfiguration
            $config.Run.Path = 'test'
            $config.Output.Verbosity = 'Detailed'
            $config.Output.CIFormat = 'GithubActions'
            $config.CodeCoverage.Enabled = $true
            $config.CodeCoverage.Path = 'src'
            Invoke-Pester -Configuration $config