on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install build dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -ErrorAction Stop
          Invoke-Build InstallBuildDependencies

      - name: Create build
        shell: pwsh
        run: Invoke-Build Build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          path: publish
          name: ${{ matrix.os }}-build
  test:
    needs: build
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          path: publish
          name: ${{ matrix.os }}-build

      - name: Install test dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -ErrorAction Stop
          Invoke-Build InstallTestDependencies

      - name: Test module
        uses: zyborg/pester-tests-report@v1
        with:
          include_paths: test
          report_name: module_tests
          report_title: Module Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Run tests
    #     shell: pwsh
    #     run: |
    #       $config = New-PesterConfiguration @{
    #         'Run.Path' = 'test'
    #         'Run.Exit' = $true
    #         'TestResult.Enabled' = $true
    #         'TestResult.OutputPath' = 'testResults.xml'
    #         'CodeCoverage.Enabled' = $true
    #         'CodeCoverage.OutputPath' = 'coverage.xml'
    #       }
    #       Invoke-Pester -Configuration $config

    #   - name: Upload test results
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: ${{ matrix.os }}-test-results
    #       path: testResults.xml

    #   - name: Upload test coverage
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: ${{ matrix.os }}-test-coverage
    #       path: coverage.xml
